### ISSUE TITLE
One button to delete them all

### ISSUE THREAD

**Issue by AnthonyMuscio** [kookma/TW-Scripts#1]
Mohammad, 

Is this where you would like contributions?

The last of the lists below is your one found at 
https://kookma.github.io/TW-Scripts/#Delete%20Buttons%20and%20a%20List%20of%20Tiddlers

The First 2 are similar but act on all tiddlers at once, with one button, although the second is simpler the first illustrates how you can address multiples inside a Button.

```
<$button>
<$list filter="[tag[Concepts]]" variable=tiddlername>
<$action-deletetiddler $tiddler=<<tiddlername>>/>
</$list>
Delete Set
</$button>

<$button>
<$action-deletetiddler $filter="[tag[Concepts]]"/>
Delete Set
</$button>

<$list filter="[tag[Concepts]]">
<$button message="tm-delete-tiddler"  >Delete</$button>
<$text text= <<currentTiddler>> /><br/>
</$list>
```

**Comment by kookma** [comment]
Many Thanks Tony!
Yes, I think this wiki can be maintained to collect and have useful scripts for working with TW.
I would like to have some of superusers, developers to be involved and help/advise to improve this
wiki. 
This wiki may help as **learn through examples** resource.

I like to let you full access to be able to directly change the contents, but I don't know how it is possible in Github.

By the way thank you for your proposed solution. I will add it to wiki. That solution was proposed by Mark.

Best
Mohammad

**Comment by kookma** [comment]
@AnthonyMuscio 
Your solution was added, tkae a look at:
https://kookma.github.io/TW-Scripts/#Delete%20Buttons%20and%20a%20List%20of%20Tiddlers
