### ISSUE TITLE
Hosting TW-Scripts as individual files

### ISSUE THREAD

**Issue by OdinJorna** [kookma/TW-Scripts#3]
Hosting TW-Scripts in the same way as Refnotes, or TiddlyWiki would make it easier to add individual solutions. It would allow people to create pull request for single .tid files instead of the whole .html file. Would that be possible to organize?

**Comment by kookma** [comment]
@OdinJorna 
Hi Odin, sure, I will do so! In the past when there were some interested people we tried an automatic build using GitHub+Travis Cl
But then as I was alone I moved to single file!

See: https://github.com/tw-scripts/TW-Scripts

I think we can shift to organization repo again!
